version: '3.6'

services:
  db:
    image: mdillon/postgis:9.6
    container_name: "aula_testes_db"
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backups:/pg_backups/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: "aula_testes_app"
    command: python /app/loggi/manage.py migrate --noinput
    command: python /app/loggi/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - 8002:8002
    depends_on:
      - db

volumes:
  pg_data: {}
  pg_backups: {}
